---
- hosts: elk
  become: yes
  gather_facts: no
  vars_files:
  - /etc/ansible/06_ELK/elk_vars
  tasks:

    - name: Cambiando Hostname 
      hostname:
        name: "{{ hostname_elk }}"

    - name: install elasticsearch rpm key
      rpm_key:
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      become: true

    - name: Repositorio Elastisearch
      copy:
        src: /etc/ansible/06_ELK/files/elasticsearch.repo
        dest: /etc/yum.repos.d/
        owner: root
        group: root
        mode: 0700
  
    - name: Repolist
      shell: yum repolist

    - name: install java & elasticsearch 6.x
      yum:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - java
        - elasticsearch
      become: true

    - name: Start and Enable elasticsearch
      systemd:
        name: elasticsearch
        state: started
        enabled: true
      become: true

    - name: Instalando Kibana
      yum:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - kibana
      become: true

    - name: Start and Enable Kibana
      systemd:
        name: kibana
        state: started
        enabled: true
      become: true

    - name: Reemplazando Linea jvm.options
      lineinfile:
        path: /etc/elasticsearch/jvm.options
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: yes
      with_items:
        - { regexp: '-Xmx1g' , line: '-Xmx2g' }
        - { regexp: '-Xms1g' , line: '-Xms2g' }

    - name: Reemplazando Linea elasticsearch.yml
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: yes
      with_items:
        - { regexp: '#bootstrap.memory_lock: true' , line: 'bootstrap.memory_lock: true' }

    - name: Reemplazando Linea elasticsearch
      lineinfile:
        path: /etc/sysconfig/elasticsearch
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: yes
      with_items:
        - { regexp: '#MAX_LOCKED_MEMORY=unlimited' , line: 'MAX_LOCKED_MEMORY=unlimited' }

    - name: Agregando Linea en elasticsearch.service
      lineinfile:
        dest: /usr/lib/systemd/system/elasticsearch.service
        regexp: ^LimitAS=infinity
        line: LimitMEMLOCK=infinity

    - name: Daemon reload
      systemd: daemon_reload=yes

    - name: Restart service elasticsearch
      service:
        name: elasticsearch
        state: restarted 

    - name: Reemplazando Linea en fstab
      lineinfile:
        path: /etc/fstab
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: yes
      with_items:
        - { regexp: '/dev/mapper/centos-swap swap                    swap    defaults        0 0' , line: '#/dev/mapper/centos-swap swap                    swap    defaults        0 0' }

#    - name: Reiniciando Maquina ELK
#      shell: shutdown -r now
#      ignore_errors: true

    - name: Reboot a Linux machine 
      reboot:
        reboot_timeout: 1800
      register: task_result

#    - name: Reboot immediately if there was a change.
#      shell: "sleep 5 && reboot"
#      async: 1
#      poll: 0
#      when: task_result is changed

#    - name: Wait for the reboot to complete if there was a change.
#      wait_for_connection:
#        connect_timeout: 20
#        sleep: 5
#        delay: 5
#        timeout: 300
#      when: task_result is changed
