- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  
  - name: create_vcenter
    vmware_guest:
      validate_certs: False
#      hostname: '192.168.1.215'
#      username: 'administrator@vsphere.local'
#      password: 'Admin2019.'
      hostname: "{{ ip_vcenter }}"
      username: "{{ user_vcenter }}"
      password: "{{ password_vcenter }}"
      folder: /
#      name: test_1
      name: "{{ name }}"
      state: poweredon
      guest_id: centos64Guest
#      esxi_hostname: '192.168.1.200'
      esxi_hostname: "{{ esxi_hostname }}"
#      datacenter: Lima-Datacenter1
      datacenter: "{{ datacenter }}"
      disk:
      - size_gb : "{{ size_gb }}" 
#        size_gb: 10        
        type: thin
#      datastore: datastore1
      datastore: "{{ datastore }}"
      hardware:
#        memory_mb: 1512
        memory_mb: "{{ memory_mb }}"  
#        num_cpus: 4
        num_cpus: "{{ num_cpus }}"
        scsi: paravirtual
      cdrom:
        type: iso
#        iso_path: "[datastore1] boot1.iso"
        iso_path: "{{ iso_path }}"
      networks:
      - name: VM Network
#        mac: aa:bb:dd:aa:00:14
        mac: "{{ mac }}"
#        ip: 10.10.10.100
        ip: "{{ ip }}"
#        netmask: 255.255.255.0
        netmask: "{{ netmask }}"
        device_type: vmxnet3
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy_vm
