- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: Create a virtual machine on given ESXi hostname
    vmware_guest:
      validate_certs: False
      hostname: '192.168.1.215'
      username: 'administrator@vsphere.local'
      password: 'Admin2019.'
      name: test_vm_0001
      state: poweredoff
    delegate_to: localhost

