- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: Create a virtual machine on given ESXi hostname
    vmware_guest:
      validate_certs: False
      hostname: '192.168.1.215'
      username: 'administrator@vsphere.local'
      password: 'Admin2019.'
      folder: /
      name: test_vm_0001
      state: poweredon
      guest_id: centos64Guest
      esxi_hostname: '192.168.1.200'
      datacenter: Lima-Datacenter1
      disk:
      - size_gb: 10
        type: thin
      datastore: datastore1
      hardware:
        memory_mb: 512
        num_cpus: 4
        scsi: paravirtual
      networks:
      - name: VM Network
        mac: aa:bb:dd:aa:00:14
        ip: 10.10.10.100
        netmask: 255.255.255.0
        device_type: vmxnet3
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy_vm
