apiVersion: v1
baseDomain: "{{ name_domain }}" 
compute:
- hyperthreading: "{{ value_compute }}"   
  name: "{{ name_compute }}"
  replicas: "{{ replicas_compute }}"
controlPlane:
  hyperthreading: "{{ value_controlplane }}"   
  name: "{{ name_ controlplane }}"
  replicas: "{{ replicas_controlplane }}"
metadata:
  name: "{{ name_metadata }}"
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '"{{ pull_secret }}"' 
sshKey: '{{ llave_ssh }}'
