---
- name: Creacion
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - /etc/ansible/01_AWS/variable.yml

  tasks:

    #Creación Llave#
    - name: Create a new SSH keypair
      ec2_key:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        aws_region: "{{ aws_region }}"
        name: "{{ nombre_llave }}"
      register: keypair

    - name: Write the key to a file
      copy:
        content: "{{ keypair.key.private_key }}"
        dest: files/{{ nombre_llave }}.pem
        mode: 0600
      when: keypair.changed
