---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: Detener instancia de AWS
    ec2:
        instance_ids: "{{ id_instance }}"
        state: stopped
        wait: True
        region: "{{ region }}"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
