apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: uat
  labels:
    name: uat
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
    ---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: jenkins
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-1
  namespace: dev
spec:
  hard:
    pods: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-2
  namespace: uat
spec:
  hard:
    pods: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-3
  namespace: prod
spec:
  hard:
    pods: "40"
